<?php
function zofront_perm(){
	return array('zofront show');
}

function zofront_menu(){
	 unset($items['taxonomy/term/%']); 
   $items['taxonomy/term/%'] =array(
      'title' => t('module'),
      'page callback' => 'zoshowtaxonomyofterm',
      'page arguments' => array(2),
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
   $items['eventnews'] =array(
      'title' => t('eventnews'),
      'page callback' => 'zoshoweventnews',
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
   $items['othernews'] =array(
      'title' => t('othernews'),
      'page callback' => 'zoshowothernews',
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
    $items['music'] =array(
      'title' => t('music'),
      'page callback' => 'zoshowmainmusic',
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
    $items['movies'] =array(
      'title' => t('movies'),
      'page callback' => 'zoshowmainmovies',
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
	$items['story'] =array(
      'title' => t('story'),
      'page callback' => 'zoshowmainstory',
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
   $items['focus'] =array(
      'title' => t('focus'),
      'page callback' => 'zoshowfocus',
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
   $items['cinema'] =array(
      'title' => t('Phim Rap'),
      'page callback' => 'cinema',
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
   $items['canhac'] =array(
      'title' => t('Ca nhac'),
      'page callback' => 'canhac',
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
   $items['zosearch'] =array(
      'title' => t('Ca nhac'),
      'page callback' => 'zosearch',
      'access arguments' => array('zofront show'),
      'type' => MENU_CALLBACK,
   );
	return $items;
}
function zosearch(){
	$path  = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/zosearch.css');
	$list = array();
	$output .= theme('zosearch',$list);
	return $output;
}
function canhac(){
	$path  = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/canhac.css');
	$list = array();
	$output .= theme('canhac',$list);
	return $output;
}
function cinema(){
	$path  = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/cinema.css');
	$list = array();
	$output .= theme('cinema',$list);
	return $output;
}

function zoshowfocus(){
	$result = pager_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE (node.type not in ("main_slide")) AND (node.sticky <> 0) ORDER BY node_created DESC',8,0,NULL);	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$typetitle = 'SỰ KIỆN NỔI BẬT';
	$output .= theme('public_zofront_term',$list,$typetitle);
	return $output;
	
}

function zoshowmainmusic(){
	$path = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/music.css');
	$result1 = db_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("music") ORDER BY node_created DESC LIMIT 0,4');
    while ($rows1 = db_fetch_object($result1)) {
		$node1 = node_load($rows1->nid);
		$queryorther .= ' AND node.nid != '.$rows1->nid;
		$list1[] = $node1;
	}
	$result = pager_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("music")'.$queryorther.' ORDER BY node_created DESC',8,0,NULL);	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$titlesukienmoi = 'SỰ KIỆN MỚI';
	$output .= theme('slide_show_music',$list1);
	$output .= theme('public_zofront_term',$list,$titlesukienmoi);
	return $output;
	
	
}

function zoshowmainmovies(){
	
	$path = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/film.css');
	
	$result = db_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("movies") ORDER BY node_created DESC LIMIT 0,4');
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('slide_show_movies',$list);
	
	//dang chieu
	$today = getdate();
	
	$dayset = $today['year'].'-'.$today['mon'].'-'.$today['mday'];
	$resultdangchieu = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node LEFT JOIN content_field_ngay_dien node_data_field_ngay_dien ON node.vid = node_data_field_ngay_dien.vid WHERE (DATE_FORMAT(ADDTIME(FROM_UNIXTIME(node_data_field_ngay_dien.field_ngay_dien_value), SEC_TO_TIME(25200)), "%%Y-%%m-%%d") <= "%s") AND (node.type in ("movies")) ORDER BY node_created DESC',$dayset);
    while ($rowcs = db_fetch_object($resultdangchieu)) {
		$nodedangchieu = node_load($rowcs->nid);
		$listdangchieu[] = $nodedangchieu;
	}
	$titledangchieu = 'ĐANG CHIẾU';
   	$output .= theme('show_trinhchieu',$listdangchieu,$titledangchieu);
   	
   	$resultsapchieu = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node LEFT JOIN content_field_ngay_dien node_data_field_ngay_dien ON node.vid = node_data_field_ngay_dien.vid WHERE (DATE_FORMAT(ADDTIME(FROM_UNIXTIME(node_data_field_ngay_dien.field_ngay_dien_value), SEC_TO_TIME(25200)), "%%Y-%%m-%%d") > "%s") AND (node.type in ("movies")) ORDER BY node_created DESC',$dayset);
    while ($rowss = db_fetch_object($resultsapchieu)) {
		$nodesapchieu = node_load($rowss->nid);
		$listsapchieu[] = $nodesapchieu;
	}
	$titlesapchieu = 'SẮP CHIẾU';
   	$output .= theme('show_trinhchieu',$listsapchieu,$titlesapchieu);
	return $output;
}

function zoshowmainstory(){
	$path = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/film.css');
	
	$result = db_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("kich_noi") ORDER BY node_created DESC LIMIT 0,4');
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('slide_show_kich_noi',$list);
	
	//dang chieu
	$today = getdate();
	
	$dayset = $today['year'].'-'.$today['mon'].'-'.$today['mday'];
	$resultdangchieu = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node LEFT JOIN content_field_ngay_dien node_data_field_ngay_dien ON node.vid = node_data_field_ngay_dien.vid WHERE (DATE_FORMAT(ADDTIME(FROM_UNIXTIME(node_data_field_ngay_dien.field_ngay_dien_value), SEC_TO_TIME(25200)), "%%Y-%%m-%%d") <= "%s") AND (node.type in ("kich_noi")) ORDER BY node_created DESC',$dayset);
    while ($rowcs = db_fetch_object($resultdangchieu)) {
		$nodedangchieu = node_load($rowcs->nid);
		$listdangchieu[] = $nodedangchieu;
	}
	$titledangchieu = 'ĐANG DIỄN';
   	$output .= theme('show_trinhchieu',$listdangchieu,$titledangchieu);
   	
   	$resultsapchieu = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node LEFT JOIN content_field_ngay_dien node_data_field_ngay_dien ON node.vid = node_data_field_ngay_dien.vid WHERE (DATE_FORMAT(ADDTIME(FROM_UNIXTIME(node_data_field_ngay_dien.field_ngay_dien_value), SEC_TO_TIME(25200)), "%%Y-%%m-%%d") > "%s") AND (node.type in ("kich_noi")) ORDER BY node_created DESC',$dayset);
    while ($rowss = db_fetch_object($resultsapchieu)) {
		$nodesapchieu = node_load($rowss->nid);
		$listsapchieu[] = $nodesapchieu;
	}
	$titlesapchieu = 'SẮP DIỄN';
   	$output .= theme('show_trinhchieu',$listsapchieu,$titlesapchieu);
	return $output;
}

function zoshowothernews(){
	$result = pager_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("su_kien_khac") ORDER BY node_created DESC',8,0,NULL);	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$typetitle = 'SỰ KIỆN KHÁC';
	$output .= theme('public_zofront_term',$list,$typetitle);
	return $output;
}


function zoshoweventnews(){
$result = pager_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type not in ("main_slide") ORDER BY node_created DESC',8,0,NULL);
	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$typetitle = 'SỰ KIỆN MỚI';
	$output .= theme('public_zofront_term',$list,$typetitle);
	return $output;
}

function zoshowtaxonomyofterm($termid){
    $checkpaent = taxonomy_get_children($termid);
    $getlist = array_keys($checkpaent);
    if (!empty($checkpaent)){    	

    	$valuearg1 = $getlist[0];
    	$valuearg2 = $getlist[1];
    $result = pager_query('SELECT node.nid AS nid,
   node.title AS node_title,
   node.created AS node_created
 FROM node node 
 LEFT JOIN term_node term_node ON node.vid = term_node.vid
 LEFT JOIN term_data term_data ON term_node.tid = term_data.tid
 LEFT JOIN term_hierarchy term_hierarchy ON term_data.tid = term_hierarchy.tid
 WHERE term_hierarchy.parent = %d OR term_hierarchy.parent = %d GROUP BY node.nid
   ORDER BY node_created DESC',8,0,NULL,$valuearg1,$valuearg2);
    	while ($rows = db_fetch_object($result)) {
		
	    $node = node_load($rows->nid);
		$list[] = $node;
	}

		$path  = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/cinema.css');
	$nametitle = taxonomy_get_term($termid)->name;
    $output .= theme('cinema',$list,$nametitle);
	return $output;
    }else {
    	$vocabularyname = taxonomy_get_term($termid);
      if($vocabularyname->vid == 3){
      	 $result = pager_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node INNER JOIN term_node term_node ON node.vid = term_node.vid WHERE term_node.tid = %d ORDER BY node_created DESC',8,0,NULL,$termid);	
 	while ($rows = db_fetch_object($result)) {
		
	    $node = node_load($rows->nid);
		$list[] = $node;
	}
		$path  = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/canhac.css');
	$nametitle = taxonomy_get_term($termid)->name;
    $output .= theme('canhac',$list,$nametitle);
	return $output;
      }else {
      	 $result = pager_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node INNER JOIN term_node term_node ON node.vid = term_node.vid WHERE term_node.tid = %d ORDER BY node_created DESC',8,0,NULL,$termid);	
 	while ($rows = db_fetch_object($result)) {
		
	    $node = node_load($rows->nid);
		$list[] = $node;
	}
	$nametitle = taxonomy_get_term($termid)->name;
    $output .= theme('public_zofront_term',$list,$nametitle);
	return $output;
      }

    }

}



function zofront_block($op = 'list', $delta = 0, $edit = array()) {

  if ($op == 'list') {
    $blocks[0]['info'] = t('Banner Home');
	$blocks[1]['info'] = t('Feature Film');
	$blocks[2]['info'] = t('Feature Screenplay');
	$blocks[3]['info'] = t('Feature News');
	$blocks[4]['info'] = t('Right Calendar');
	$blocks[5]['info'] = t('Right Hot Event');
	$blocks[6]['info'] = t('Right Film');
	$blocks[7]['info'] = t('Right ScreenPlay');
	$blocks[8]['info'] = t('Right New Event');
	$blocks[9]['info'] = t('Right Smail Hot Event');
    return $blocks;
  }
  elseif ($op == 'view') {
    $block = array();

    switch ($delta) {
      case 0:
        $block['content'] = zofront_bannerhome();
        return $block;
	  case 1:
        $block['content'] = zofront_featfilm();
        return $block;
	  case 2:
        $block['content'] = zofront_featscreen();
        return $block;	
	  case 3:
        $block['content'] = zofront_featnews();
        return $block;	
	  case 4:
        $block['content'] = zofront_calendar();
        return $block;	
	  case 5:
        $block['content'] = zofront_hot_event();
        return $block;	
	  case 6:
        $block['content'] = zofront_right_film();
        return $block;	
	  case 7:
        $block['content'] = zofront_right_screen();
        return $block;		
	  case 8:
        $block['content'] = zofront_right_new_event();
        return $block;	
	  case 9:
        $block['content'] = zofront_right_smail_hot_event();
        return $block;	
    }
  }
}

function zofront_right_smail_hot_event(){
	$result = db_query('SELECT node.nid AS nid FROM node node WHERE (node.type not in ("main_slide")) AND (node.sticky <> 0)');
     while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_right_smail_hot_event',$list);
	return $output;	
}

function zofront_right_new_event(){
   $result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE (node.type not in ("main_slide")) ORDER BY node_created DESC LIMIT 0,4');
	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_right_new_event',$list);
	return $output;	
}

function zofront_right_film(){
   $result = db_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("movies") ORDER BY node_created DESC LIMIT 0,6');
     while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_right_film',$list);
	return $output;	
}

function zofront_right_screen(){
   $result = db_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("kich_noi") ORDER BY node_created DESC LIMIT 0,6');
     while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_right_screen',$list);
	return $output;	
}

function zofront_hot_event(){
	

	$result = db_query('SELECT node.nid AS nid FROM node node WHERE (node.type not in ("main_slide")) AND (node.sticky <> 0)');
     while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_hot_event',$list);
	return $output;
}

function zofront_calendar(){
	$list ='';
	$output .= theme('zofront_calendar',$list);
	return $output;
}

function zofront_bannerhome(){
	$query .= 'SELECT * ';
	$query .= 'FROM {node} n ';
	$query .= 'WHERE n.type in ("main_slide") ';
	$query .= 'AND n.status  = 1 ';
	$query .= 'ORDER BY n.nid DESC ';
	$query .= 'LIMIT 0,4 ';
	$list ='';
	
	$result = db_query($query);
	while($row = db_fetch_object($result)){
		$list[] = node_load($row->nid);
	}
	
	$output .= theme('zofront_bannerhome',$list);
	return $output;
}

function zofront_featfilm(){
	$path = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/featurefilm.css');
	drupal_add_js($path.'/js/jquery.roundabout.js');
	$list ='';
	$result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE node.type in ("movies") ORDER BY node_created DESC LIMIT 0,4');
    while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_featfilm',$list);
	return $output;
}

function zofront_featscreen(){
	$path = drupal_get_path('module','zofront');
	drupal_add_js($path.'/js/amazon_scroller.js');
	drupal_add_css($path.'/css/amazon_scroller.css');
    $result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE node.type in ("kich_noi") ORDER BY node_created DESC LIMIT 0,8');
    while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE node.type in ("kich_noi")	ORDER BY node_created DESC LIMIT 0,4');
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_featscreen',$list);
	return $output;
}

function zofront_featnews(){
	$result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE (node.type not in ("main_slide")) ORDER BY node_created DESC LIMIT 0,4');
	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_featnews',$list);
	return $output;
}


function template_preprocess_zofront_bannerhome(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_featfilm(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_featscreen(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_featnews(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_calendar(&$variables){
	 $variables['list'] = $variables['list'];
}

function template_preprocess_public_zofront_term(&$variables){
	 $variables['list'] = $variables['list'];
	 $variables['type'] = $variables['type'];
}

function template_preprocess_zofront_hot_event(&$variables){
	 $variables['list'] = $variables['list'];
}

function template_preprocess_slide_show_music(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_slide_show_movies(&$variables){
	 $variables['list'] = $variables['list'];
}

function template_preprocess_show_trinhchieu(&$variables){
	 $variables['list'] = $variables['list'];
	 $variables['type'] = $variables['type'];
}

function template_preprocess_slide_show_kich_noi(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_right_screen(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_right_film(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_right_new_event(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_right_smail_hot_event(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_cinema(&$variables){
	 $variables['list'] = $variables['list'];
	 $variables['type'] = $variables['type'];
}
function template_preprocess_canhac(&$variables){
	 $variables['list'] = $variables['list'];
	 $variables['type'] = $variables['type'];
}
function template_preprocess_zosearch(&$variables){
	 $variables['list'] = $variables['list'];
}

function zofront_theme(){
	return array(
	  'zofront_bannerhome' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_bannerhome',
      ),
      'zofront_featfilm' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_featfilm',
      ),
      'zofront_featscreen' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_featscreen',
      ),
      'zofront_featnews' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_featnews',
      ),
      'zofront_calendar' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_calendar',
      ),

      'public_zofront_term' => array(
	      'arguments' => array('list'=>NULL,'type'=>NULL),
		  'template' => 'public_zofront_term',
      ),

      'zofront_hot_event' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_hot_event',
      ),
      'slide_show_music' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'slide_show_music',
      ),
	  'slide_show_movies' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'slide_show_movies',
      ),
      'slide_show_kich_noi' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'slide_show_kich_noi',
      ),
      'show_trinhchieu' => array(
	      'arguments' => array('list'=>NULL,'type'=>NULL),
		  'template' => 'show_trinhchieu',
      ),
      'zofront_right_screen' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_right_screen',
      ),
      'zofront_right_film' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_right_film',
      ),
      'zofront_right_new_event' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_right_new_event',
      ),
      'zofront_right_smail_hot_event' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_right_smail_hot_event',
      ),
      'cinema' => array(
	      'arguments' => array('list'=>NULL,'type'=>NULL),
		  'template' => 'cinema',
      ),
      'canhac' => array(
	      'arguments' => array('list'=>NULL,'type'=>NULL),
		  'template' => 'canhac',
      ),
      'zosearch' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zosearch',
      ),
	);
}

