<?php

function zofront_menu(){
	 unset($items['taxonomy/term/%']); 
   $items['taxonomy/term/%'] =array(
      'title' => t('module'),
      'page callback' => 'zoshowtaxonomyofterm',
      'page arguments' => array(2),
      'access arguments' => array('access term'),
      'type' => MENU_CALLBACK,
   );
   $items['eventnews'] =array(
      'title' => t('eventnews'),
      'page callback' => 'zoshoweventnews',
      'access arguments' => array('access term'),
      'type' => MENU_CALLBACK,
   );
   $items['othernews'] =array(
      'title' => t('othernews'),
      'page callback' => 'zoshowothernews',
      'access arguments' => array('access term'),
      'type' => MENU_CALLBACK,
   );
    $items['music'] =array(
      'title' => t('music'),
      'page callback' => 'zoshowmainmusic',
      'access arguments' => array('access term'),
      'type' => MENU_CALLBACK,
   );
    $items['movies'] =array(
      'title' => t('movies'),
      'page callback' => 'zoshowmainmovies',
      'access arguments' => array('access term'),
      'type' => MENU_CALLBACK,
   );
	$items['story'] =array(
      'title' => t('story'),
      'page callback' => 'zoshowmainstory',
      'access arguments' => array('access term'),
      'type' => MENU_CALLBACK,
   );
	return $items;
}


function zoshowmainmusic(){
		$result = pager_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("music") ORDER BY node_created DESC',8,0,NULL);	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('public_zofront_term',$list);
	return $output;
	
	
}

function zoshowmainmovies(){
	
		$result = pager_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("movies") ORDER BY node_created DESC',8,0,NULL);	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('public_zofront_term',$list);
	return $output;
}

function zoshowmainstory(){
		$result = pager_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("kich_noi") ORDER BY node_created DESC',8,0,NULL);	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('public_zofront_term',$list);
	return $output;
}

function zoshowothernews(){
	$result = pager_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type in ("su_kien_khac") ORDER BY node_created DESC',8,0,NULL);	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('public_zofront_term',$list);
	return $output;
}


function zoshoweventnews(){
$result = pager_query('SELECT node.nid AS nid,node.created AS node_created FROM node node WHERE node.type not in ("main_slide") ORDER BY node_created DESC',8,0,NULL);
	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('public_zofront_term',$list);
	return $output;
}

function zoshowtaxonomyofterm($termid){
    $checkpaent = taxonomy_get_children($termid);
    $getlist = array_keys($checkpaent);
    if (!empty($checkpaent)){    	
    	
    	$valuearg1 = $getlist[0];
    	$valuearg2 = $getlist[1];
    $result = pager_query('SELECT node.nid AS nid,
   node.title AS node_title,
   node.created AS node_created
 FROM node node 
 LEFT JOIN term_node term_node ON node.vid = term_node.vid
 LEFT JOIN term_data term_data ON term_node.tid = term_data.tid
 LEFT JOIN term_hierarchy term_hierarchy ON term_data.tid = term_hierarchy.tid
 WHERE term_hierarchy.parent = %d OR term_hierarchy.parent = %d
   ORDER BY node_created DESC',8,0,NULL,$valuearg1,$valuearg2);
    }else {
 $result = pager_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node INNER JOIN term_node term_node ON node.vid = term_node.vid WHERE term_node.tid = %d ORDER BY node_created DESC',8,0,NULL,$termid);	
    }
	while ($rows = db_fetch_object($result)) {
		
	    $node = node_load($rows->nid);
		$list[] = $node;
	}
    $output .= theme('public_zofront_term',$list);
	return $output;
}



function zofront_block($op = 'list', $delta = 0, $edit = array()) {

  if ($op == 'list') {
    $blocks[0]['info'] = t('Banner Home');
	$blocks[1]['info'] = t('Feature Film');
	$blocks[2]['info'] = t('Feature Screenplay');
	$blocks[3]['info'] = t('Feature News');
	$blocks[4]['info'] = t('Right Calendar');
	$blocks[5]['info'] = t('Right Hot Event');
    return $blocks;
  }
  elseif ($op == 'view') {
    $block = array();

    switch ($delta) {
      case 0:
        $block['content'] = zofront_bannerhome();
        return $block;
	  case 1:
        $block['content'] = zofront_featfilm();
        return $block;
	  case 2:
        $block['content'] = zofront_featscreen();
        return $block;	
	  case 3:
        $block['content'] = zofront_featnews();
        return $block;	
	  case 4:
        $block['content'] = zofront_calendar();
        return $block;	
	  case 5:
        $block['content'] = zofront_hot_event();
        return $block;		
    }
  }
}

function zofront_hot_event(){
	
	$list ='';	
	$result = db_query('SELECT node.nid AS nid FROM node node WHERE (node.type not in ("main_slide")) AND (node.sticky <> 0)');
     while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_hot_event',$list);
	return $output;
}

function zofront_calendar(){
	$list ='';
	$output .= theme('zofront_calendar',$list);
	return $output;
}

function zofront_bannerhome(){
	$query .= 'SELECT * ';
	$query .= 'FROM {node} n ';
	$query .= 'WHERE n.type in ("main_slide") ';
	$query .= 'AND n.status  = 1 ';
	$query .= 'ORDER BY n.nid DESC ';
	$query .= 'LIMIT 0,4 ';
	$list ='';
	
	$result = db_query($query);
	while($row = db_fetch_object($result)){
		$list[] = node_load($row->nid);
	}
	
	$output .= theme('zofront_bannerhome',$list);
	return $output;
}

function zofront_featfilm(){
	$path = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/featurefilm.css');
	drupal_add_js($path.'/js/jquery.roundabout.js');
	$list ='';
	$result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE node.type in ("movies") ORDER BY node_created DESC LIMIT 0,4');
    while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_featfilm',$list);
	return $output;
}

function zofront_featscreen(){
	$path = drupal_get_path('module','zofront');
	drupal_add_js($path.'/js/amazon_scroller.js');
	drupal_add_css($path.'/css/amazon_scroller.css');
    $result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE node.type in ("kich_noi") ORDER BY node_created DESC LIMIT 0,8');
    while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE node.type in ("kich_noi")	ORDER BY node_created DESC LIMIT 0,4');
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_featscreen',$list);
	return $output;
}

function zofront_featnews(){
	$result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node ORDER BY node_created DESC LIMIT 0,4');
	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_featnews',$list);
	return $output;
}


function template_preprocess_zofront_bannerhome(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_featfilm(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_featscreen(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_featnews(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_calendar(&$variables){
	 $variables['list'] = $variables['list'];
}

function template_preprocess_public_zofront_term(&$variables){
	 $variables['list'] = $variables['list'];
}

function template_preprocess_zofront_hot_event(&$variables){
	 $variables['list'] = $variables['list'];
}



function zofront_theme(){
	return array(
	  'zofront_bannerhome' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_bannerhome',
      ),
      'zofront_featfilm' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_featfilm',
      ),
      'zofront_featscreen' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_featscreen',
      ),
      'zofront_featnews' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_featnews',
      ),
      'zofront_calendar' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_calendar',
      ),

      'public_zofront_term' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'public_zofront_term',
      ),

      'zofront_hot_event' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_hot_event',
      ),

	);
}

