<?php

function zofront_menu(){
	 unset($items['taxonomy/term/%']); 
   $items['taxonomy/term/%'] =array(
      'title' => t('module'),
      'page callback' => 'zoshowtaxonomyofterm',
      'page arguments' => array(2),
      'access arguments' => array('access term'),
      'type' => MENU_CALLBACK,
   );

	
	return $items;
}


function zoshowtaxonomyofterm($termid){
  
	$result = pager_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node INNER JOIN term_node term_node ON node.vid = term_node.vid WHERE term_node.tid = %d ORDER BY node_created DESC',8,0,NULL,$termid);
	while ($rows = db_fetch_object($result)) {
	    $node = node_load($rows->nid);
		$list[] = $node;
	}
    $output .= theme('public_zofront_term',$list);
	return $output;
}



function zofront_block($op = 'list', $delta = 0, $edit = array()) {

  if ($op == 'list') {
    $blocks[0]['info'] = t('Banner Home');
	$blocks[1]['info'] = t('Feature Film');
	$blocks[2]['info'] = t('Feature Screenplay');
	$blocks[3]['info'] = t('Feature News');
	$blocks[4]['info'] = t('Right Calendar');
	$blocks[5]['info'] = t('Right Hot Event');
    return $blocks;
  }
  elseif ($op == 'view') {
    $block = array();

    switch ($delta) {
      case 0:
        $block['content'] = zofront_bannerhome();
        return $block;
	  case 1:
        $block['content'] = zofront_featfilm();
        return $block;
	  case 2:
        $block['content'] = zofront_featscreen();
        return $block;	
	  case 3:
        $block['content'] = zofront_featnews();
        return $block;	
	  case 4:
        $block['content'] = zofront_calendar();
        return $block;	
	  case 5:
        $block['content'] = zofront_hot_event();
        return $block;		
    }
  }
}

function zofront_hot_event(){
	$list ='';
	$output .= theme('zofront_hot_event',$list);
	return $output;
}

function zofront_calendar(){
	$list ='';
	$output .= theme('zofront_calendar',$list);
	return $output;
}

function zofront_bannerhome(){
	$list ='';
	$output .= theme('zofront_bannerhome',$list);
	return $output;
}

function zofront_featfilm(){
	$path = drupal_get_path('module','zofront');
	drupal_add_css($path.'/css/featurefilm.css');
	$result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE node.type in ("movies") ORDER BY node_created DESC LIMIT 0,4');
    while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_featfilm',$list);
	return $output;
}

function zofront_featscreen(){
	$path = drupal_get_path('module','zofront');
	drupal_add_js($path.'/js/amazon_scroller.js');
	drupal_add_css($path.'/css/amazon_scroller.css');
    $result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node WHERE node.type in ("kich_noi") ORDER BY node_created DESC LIMIT 0,8');
    while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_featscreen',$list);
	return $output;
}

function zofront_featnews(){
	$result = db_query('SELECT node.nid AS nid,node.title AS node_title,node.created AS node_created FROM node node ORDER BY node_created DESC LIMIT 0,4');
	
	while ($rows = db_fetch_object($result)) {
		$node = node_load($rows->nid);
		$list[] = $node;
	}
	$output .= theme('zofront_featnews',$list);
	return $output;
}


function template_preprocess_zofront_bannerhome(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_featfilm(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_featscreen(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_featnews(&$variables){
	 $variables['list'] = $variables['list'];
}
function template_preprocess_zofront_calendar(&$variables){
	 $variables['list'] = $variables['list'];
}

function template_preprocess_public_zofront_term(&$variables){
	 $variables['list'] = $variables['list'];
}

function template_preprocess_zofront_hot_event(&$variables){
	 $variables['list'] = $variables['list'];
}



function zofront_theme(){
	return array(
	  'zofront_bannerhome' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_bannerhome',
      ),
      'zofront_featfilm' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_featfilm',
      ),
      'zofront_featscreen' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_featscreen',
      ),
      'zofront_featnews' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_featnews',
      ),
      'zofront_calendar' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_calendar',
      ),

      'public_zofront_term' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'public_zofront_term',
      ),

      'zofront_hot_event' => array(
	      'arguments' => array('list'=>NULL),
		  'template' => 'zofront_hot_event',
      ),

	);
}

