<?php 

function cotolog_movies_perm(){
	return array('create cololog movies');
}

function cotolog_movies_menu(){
	  $items = array();
   $items['admin/mamagerca'] = array(
   'title' => 'Đăng ký các thể loại',
    'description' => 'Đăng ký rạp chiếu phim.',
   'page callback' => 'drupal_get_form',
    'page arguments' => array('cotolog_movies_form'),
   'access arguments' => array('create cololog movies'),
   );
  $items['admin/mamagerca/cotologmovies'] = array(
    'title' => 'Đăng ký rạp chiếu phim',
    'description' => 'Đăng ký rạp chiếu phim.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cotolog_movies_form'),
    'access arguments' => array('create cololog movies'),
    );
  $items['admin/mamagerca/cotologmovies/listcotologmovies'] = array(
    'title' => 'Danh sách rạp chiếu phim',
    'description' => 'Đăng ký rạp chiếu phim.',
    'page callback' => 'listcotologmovies',
    'access arguments' => array('create cololog movies'),
    );
  $items['admin/mamagerca/cotologmusics'] = array(
    'title' => 'Đăng ký Thể loại ca nhạc',
    'description' => 'Đăng ký Thể loại ca nhạc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cotolog_musics_form'),
    'access arguments' => array('create cololog movies'),
    );
  $items['admin/mamagerca/cotologmusics/listcotologmusics'] = array(
    'title' => 'Danh sách thể loại ca nhạc',
    'description' => 'Danh sách thể loại ca nhạc',
    'page callback' => 'listcotologmusics',
    'access arguments' => array('create cololog movies'),
    );
   $items['admin/mamagerca/cotologkichs'] = array(
    'title' => 'Đăng ký rạp diễn kịch',
    'description' => 'Đăng ký rạp diễn kịch nói',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cotolog_kichs_form'),
    'access arguments' => array('create cololog movies'),
    );
   $items['admin/mamagerca/cotologkichs/listcotologkichs'] = array(
    'title' => 'Danh sách rạp diễn kịch',
    'description' => 'Đăng ký rạp diễn kịch nói',
    'page callback' => 'listcotologkichs',
    'access arguments' => array('create cololog movies'),
    );
    $items['admin/deleteca'] = array(
    'title' => 'Xóa',
    'description' => 'Xóa',
    'page callback' => 'deletecaterm',
    'access arguments' => array('create cololog movies'),
    'type' => MENU_CALLBACK,
    );
    
  return $items;
}

function deletecaterm(){


	$termid = arg(2);
    taxonomy_del_term($termid);
    drupal_set_message('Đã xóa thành công');
	drupal_goto($_REQUEST['destination']);
	
	return 'this is my lab';
}


function listcotologmusics(){
		$listmovies = taxonomy_get_tree(3,0,-1,1);
	
	  $rows = array();


 foreach ($listmovies as $key){
     $rows[] = array(//row
      'data' => array( //row data
        array( //Cell1
          'data' => $key->tid,
          'class' => '',
        ),
        array( 
          'data' => $key->name,
          'class' => '',
        ),
        array( 
          'data' => l('xóa','admin/deleteca/'.$key->tid, array('query' => drupal_get_destination(),'html'=>true)),
          'class' => '',
        ),
        array( 
          'data' => l('Sửa','admin/content/taxonomy/edit/term/'.$key->tid, array('query' => drupal_get_destination(),'html'=>true)),
          'class' => '',
        ),
      ),//endrow
      'class' => '', //row class
    );//endrow
  }
  $header = array(
    array('data' => t('Mã số')),
    array('data' => t('Tên')),
    array('data' => t('Xóa')),
    array('data' => t('Sửa')),
  );
  $output = theme_table($header, $rows);
  return $output;
}

function listcotologkichs(){
		$listmovies = taxonomy_get_tree(4,0,-1,1);
	
	  $rows = array();


 foreach ($listmovies as $key){
     $rows[] = array(//row
      'data' => array( //row data
        array( //Cell1
          'data' => $key->tid,
          'class' => '',
        ),
        array( 
          'data' => $key->name,
          'class' => '',
        ),
        array( 
          'data' => l('xóa','admin/deleteca/'.$key->tid, array('query' => drupal_get_destination(),'html'=>true)),
          'class' => '',
        ),
        array( 
          'data' => l('Sửa','admin/content/taxonomy/edit/term/'.$key->tid, array('query' => drupal_get_destination(),'html'=>true)),
          'class' => '',
        ),
      ),//endrow
      'class' => '', //row class
    );//endrow
  }
  $header = array(
    array('data' => t('Mã số')),
    array('data' => t('Tên')),
    array('data' => t('Xóa')),
    array('data' => t('Sửa')),
  );
  $output = theme_table($header, $rows);
  return $output;
}

function listcotologmovies(){
	$listmovies = taxonomy_get_tree(2,0,-1,1);
	
	  $rows = array();


 foreach ($listmovies as $key){
     $rows[] = array(//row
      'data' => array( //row data
        array( //Cell1
          'data' => $key->tid,
          'class' => '',
        ),
        array( 
          'data' => $key->name,
          'class' => '',
        ),
        array( 
          'data' => l('xóa','admin/deleteca/'.$key->tid, array('query' => drupal_get_destination(),'html'=>true)),
          'class' => '',
        ),
        array( 
          'data' => l('Sửa','admin/content/taxonomy/edit/term/'.$key->tid, array('query' => drupal_get_destination(),'html'=>true)),
          'class' => '',
        ),
      ),//endrow
      'class' => '', //row class
    );//endrow
  }
  $header = array(
    array('data' => t('Mã số')),
    array('data' => t('Tên')),
    array('data' => t('Xóa')),
    array('data' => t('Sửa')),
  );
  $output = theme_table($header, $rows);
  return $output;

}
function cotolog_kichs_form(){
	$form['name'] = array(
      '#type' => 'textfield', 
      '#title' => t('Tên thể loại ca nhạc'), 
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('submit')
    );
    return $form;
}

function cotolog_kichs_form_submit($form,&$form_sate){
	$term = array( 'vid' => 4, 'name' => $form_sate['values']['name'], 'parent' => 0 );
	taxonomy_save_term($term);
	drupal_set_message('Đã lưu thành công');
}

function cotolog_musics_form(){
	$form['name'] = array(
      '#type' => 'textfield', 
      '#title' => t('Tên thể loại ca nhạc'), 
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('submit')
    );
    return $form;
}

function cotolog_musics_form_submit($form,&$form_sate){
	$term = array( 'vid' => 3, 'name' => $form_sate['values']['name'], 'parent' => 0 );
	taxonomy_save_term($term);
	drupal_set_message('Đã lưu thành công');
}


function cotolog_movies_form(){
	$form['name'] = array(
      '#type' => 'textfield', 
      '#title' => t('Tên rạp chiếu'), 
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('submit')
    );
    return $form;
}

function cotolog_movies_form_submit($form,&$form_sate){
	$terms = array(
    $form_sate['values']['name'] => array(
      '2D' => array('06:00 AM','07:00 AM','08:00 AM','09:00 AM','10:00 AM','11:00 AM','12:00 AM','01:00 PM','02:00 PM','03:00 PM','04:00 PM','05:00 PM','06:00 PM','07:00 PM','08:00 PM','09:00 PM','10:00 PM','11:00 PM'),
      '3D' => array('06:00 AM','07:00 AM','08:00 AM','09:00 AM','10:00 AM','11:00 AM','12:00 AM','01:00 PM','02:00 PM','03:00 PM','04:00 PM','05:00 PM','06:00 PM','07:00 PM','08:00 PM','09:00 PM','10:00 PM','11:00 PM'),
      )
      );
	cotolog_movies_save_terms_recursive(2,$terms);
	drupal_set_message('Đã lưu thành công');
}

function cotolog_movies_save_terms_recursive( $vid, &$terms, $ptid=0 ) {
  foreach ( $terms as $k => $v ) {
    $name = is_string( $k ) ? $k : $v;
    $term = array( 'vid' => $vid, 'name' => $name, 'parent' => $ptid );
    taxonomy_save_term( $term );
    if ( is_array( $v ) && count( $v ) )
      cotolog_movies_save_terms_recursive( $vid, $terms[ $k ], $term[ 'tid' ] );
  }
}